Added API stubs necessary for the next task.
Guide-Health-Coach/admin-dashboard-web pull request #8
Opened 2024-04-12 19:38 UTC by tommyp101

2024-04-12 20:30 UTC, akdombrowski commented
was that me that accidentally installed with yarn?
i use it for my projects and it's a habit

2024-04-12 20:44 UTC, akdombrowski requested changes

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/clients/addClientResponses.ts
> + * @param {string} clientId - The email or phone number of the client submitting the response.
if it's one of either email or phone, I would just make 2 optional params and make sure one exists. it'll be easier if you know a variable is the same "type" to work with it

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/clients/addClientResponses.ts
> + * @param {string} clientId - The email or phone number of the client submitting the response.
and reserve id for some kind of guuid-like string

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/clients/addClientResponses.ts
> +export default async function addClientResponses(clientId, clientResponses) {
it's not a hard rule, but I've found a good practice in general is to make the param and object by default. If you add another key to the object later to take in another param, it won't break things vs adding another one here

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/clients/addClientResponses.ts
> +    return fetch('https://api.example.com/add-client-responses', {
api.example.com?

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/coaches/getClientResponses.ts
> +export default async function getUserAnswers(userId) {
consistent naming with file

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/coaches/getPublishStatus.ts
> +export default async function getCoachQuestionStatus(coachEmail) {
same. consistent naming

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/fetchQuestions.ts
> +export default async function fetchCoachQuestions(coachEmail) {
naming

2024-04-12 20:44 UTC, akdombrowski commented on tsconfig.json
was this intentional?

2024-04-12 20:44 UTC, akdombrowski commented on src/app/onboarding/[linkId]/page.tsx
why is this its own page?

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/coaches/getPublishStatus.ts
> +        body: JSON.stringify({ email: coachEmail })
I don't think you need an object as the body + it's a GET anyways.

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/coaches/getClientResponses.ts
> +    return fetch(`https://api.example.com/get-user-answers/${userId}`, {
if this is an email with `@` in it, will it work?

2024-04-12 20:44 UTC, akdombrowski commented on src/app/api/coaches/getPublishStatus.ts
is there a setter along with this?

2024-04-12 20:44 UTC, akdombrowski commented on src/actions/link/generateLink.ts
>      const newLink = `${baseUrl}/onboarding/${linkId}`;
we can change the name later, not a big deal, but these questions don't necessarily have to be just for onboarding

2024-04-12 20:44 UTC, akdombrowski commented on src/actions/link/generateLink.ts
>      const linkId = nanoid(); // Generates a unique ID
we agreed to use coach's name

2024-04-13 17:04 UTC, tommyp101 commented
> was that me that accidentally installed with yarn? i use it for my projects and it's a habit

I'm not sure but I saw the yarn lock when I pulled, so I yarn install'd and it worked, just didn't deploy properly.

2024-04-16 02:14 UTC, merged